# Generated by Django 3.0.2 on 2020-05-14 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default=uuid.UUID('f97fd777-350a-4213-9b1f-2f41fc885304'), max_length=255),
        ),
    ]
