# Generated by Django 3.0.2 on 2020-05-20 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default=uuid.UUID('35c1d599-e2cf-4c7d-98f7-7da6a30bc0c3'), max_length=255),
        ),
    ]
