# Generated by Django 3.0.2 on 2020-05-15 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200514_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default=uuid.UUID('2577ae90-1153-448f-943f-91095d628261'), max_length=255),
        ),
    ]
