# Generated by Django 3.0.2 on 2020-05-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200515_1014'),
        ('accounts', '0002_auto_20200520_2021'),
    ]

    operations = [
    ]
