# Generated by Django 3.0.2 on 2020-02-10 08:49

from django.core.management import BaseCommand
from django.core.management import call_command
from django.contrib.auth.models import User, Group
from accounts.util import create_user


class Command(BaseCommand):

    def handle(self, *args, **kwargs):
        self.name_list = ["kim", "steinar", "thomas", "nikolai", "andreas", "christer"]

        for name in range(len(self.name_list)):
            u = create_user(
                groups=["worker"],
                username=self.name_list[name],
                password="passord1234",
                email=self.name_list[name]+"@"+self.name_list[name]+".com",
                first_name=self.name_list[name],
            )
            if u:
                self.stdout.write(f"Created {self.name_list[name]}, password is passord1234")
            else:
                self.stdout.write(f"Failed to create {self.name_list[name]} user")
