# Generated by Django 3.0.2 on 2020-02-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='schema',
            name='issue',
            field=models.CharField(max_length=100),
        ),
    ]
